# Generated by Django 2.0.5 on 2018-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shohin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinmoku', models.CharField(max_length=20)),
                ('hinmei', models.CharField(max_length=100)),
                ('zaiko', models.IntegerField(default=0)),
            ],
        ),
    ]
